export const MARKETER_HOMEPAGE = '/marketer';
export const PUBLISHER_SIGN_UP_ROUTE = '/creator/register';
// export const PUBLISHER_DASHBOARD_PAY_PER_SALE_ROUTE = '/creator/sales/dashboard'
// export const PUBLISHER_DASHBOARD_PER_PER_CLICK_ROUTE = '/creator/clicks/dashboard'
export const PUBLISHER_DASHBOARD_ROUTE_WITH_PARAM = '/creator/dashboard';
export const MARKETER_FEED_ROUTE = '/marketer/feed';
export const PUBLISHER_FEED_ROUTE = '/creator/feed';
export const PUBLISHER_WITHDRAW_ROUTE_WITH_PARAM = '/creator/withdraw';
export const PUBLISHER_CAMPAIGNS_HISTORY_ROUTE = '/creator/history';
export const PUBLISHER_WORKFLOW_ROUTE = '/creator/workflow';
export const PUBLISHER_GA_CONNECT_ROUTE = '/creator/connect';
export const MARKETER_SIGN_UP_ROUTE = '/marketer/register';
export const MARKETER_WITHDRAW_ROUTE = '/marketer/withdraw';
export const SIGN_UP_FALLBACK_ROUTE = '/register';
export const PTOKENS_SWAP_ROUTE = '/ptokens';
